rpc:
  endpoint: "https://public-node.testnet.rsk.co"

transfer:
  key: 4f8048b22554257c143c55d3d6f56fbcdf8da0465fc0912bea0dfc44c0bf31f2
  address: 0x9ac64cc6e4415144c455bd8e4837fea55603e5c3
  gas_limit: 300000
  gas_price: 3000
  time: 3s
contractdata:
  amountOutMin:
  addressArray:
  address:
  deadline:

log:
  level: debug
  disable_sentry: true
